### ISSUE TITLE
Plugin crashes with SVN repositories

### ISSUE THREAD

**Issue by jnhmn** [simeji/readme_at_repositories#13]
This plugin seems to work only with git repositories.
If I open the repository view of a SVN repository, the server returns an HTTP 500 error.

Following the output of the production log:
```Started GET "/projects/test01/repository/2" for 130.83.57.80 at 2017-07-10 14:04:37 +0200
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"test01", "repository_id"=>"2"}
  Current user: admin (id=1)
  Rendered repositories/show.html.erb within layouts/base (5.1ms)
Completed 500 Internal Server Error in 122ms (ActiveRecord: 5.1ms)

ActionView::Template::Error (undefined method `entry' for nil:NilClass):
    1: <%= call_hook(:view_repositories_show_contextual, { :repository => @repository, :project => @project }) %>
    2: 
    3: <div class="contextual">
    4:   <%= render :partial => 'navigation' %>
  plugins/readme_at_repositories/lib/display_readme.rb:17:in `view_repositories_show_contextual'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/repositories/show.html.erb:1:in `_app_views_repositories_show_html_erb___1144634906139630312_38496960'
  app/controllers/repositories_controller.rb:125:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by ayaye** [comment]
The problem seems to be with repos without id.

**Comment by simeji** [comment]
Fixed in PR #19. Added a nil check for cases where `repo.find` returns `nil` on SVN repositories, preventing the HTTP 500 crash.
