### ISSUE TITLE
Install issues with Rednime 4.0

### ISSUE THREAD

**Issue by albrechtd** [simeji/readme_at_repositories#16]
I use this *really* cool plugin on an old Redmine 3.3.1 installation, which I want to migrate to
- Redmine version 4.0.7.stable
- Ruby version 2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
- Rails version 5.2.2.1

but unfortunately the installation process failed:
```
root@redmine4:/usr/share/redmine/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /usr/share/redmine)
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/usr/share/redmine/plugins/readme_at_repositories/init.rb:17:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/redmine/lib/redmine/plugin.rb:175:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:166:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:166:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
Following the [hint in a similar bug report](https://github.com/phatworx/devise_security_extension/issues/223#issuecomment-317129505), I ran
```
sed -e 's/ActionDispatch::Callbacks.to_prepare/ActiveSupport::Reloader.to_prepare/g' -i readme_at_repositories/init.rb
```
 which “replaced” the error by a different one:
```
root@redmine4:/usr/share/redmine/plugins# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /usr/share/redmine)
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ProjectsHelper:Module
Did you mean?  alias_method
/usr/share/redmine/plugins/readme_at_repositories/lib/extend_project_setting.rb:9:in `block in included'
/usr/share/redmine/plugins/readme_at_repositories/lib/extend_project_setting.rb:7:in `class_eval'
/usr/share/redmine/plugins/readme_at_repositories/lib/extend_project_setting.rb:7:in `included'
/usr/share/redmine/plugins/readme_at_repositories/init.rb:20:in `include'
/usr/share/redmine/plugins/readme_at_repositories/init.rb:20:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:605:in `catch'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `each'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:89:in `prepare!'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/share/rubygems-integration/all/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:337:in `require_environment!'
/usr/share/rubygems-integration/all/gems/railties-5.2.2.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
Any chance to install the plugin on Redmine 4 (and maybe 4.1)?

**Comment by karippery** [comment]
I have same issue.. if anyone have solution please share it here.

**Comment by albrechtd** [comment]
Actually, the plugin *does* work with Redmine 4.0.7 from Debian Buster backports – I made the mistake to use your 0.3.0 release package instead of the latest Git master…  So you *might* want to consider tagging the current master as new release as to avoid the confusion.

Sorry for the noise!
